---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Torrent:
    - Qbittorrent:
        href: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
        description: Torrent downloader 
        icon: qbittorrent.png
        widget:
            type: qbittorrent
            url: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
            username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
    - Sonarr Anime:
        href: {{HOMEPAGE_VAR_SONARR_ANIME_URL}}
        description: Anime downloader
        icon: sonarr.png
        widget:
            type: sonarr
            url: {{HOMEPAGE_VAR_SONARR_ANIME_URL}}
            key: {{HOMEPAGE_VAR_SONARR_ANIME_API}}
    - Sonarr TV:
        href: {{HOMEPAGE_VAR_SONARR_TV_URL}}
        description: TV show downloader
        icon: sonarr.png
        widget:
            type: sonarr
            url: {{HOMEPAGE_VAR_SONARR_TV_URL}}
            key: {{HOMEPAGE_VAR_SONARR_TV_API}}
    - Radarr:
        href: {{HOMEPAGE_VAR_RADARR_URL}}
        description: Movie downloader
        icon: radarr.png
        widget:
            type: radarr
            url: {{HOMEPAGE_VAR_RADARR_URL}}
            key: {{HOMEPAGE_VAR_RADARR_API}}
    - Lidarr:
        href: {{HOMEPAGE_VAR_LIDARR_URL}}
        description: Music downloader
        icon: lidarr.png
        widget:
            type: lidarr
            url: {{HOMEPAGE_VAR_LIDARR_URL}}
            key: {{HOMEPAGE_VAR_LIDARR_API}}
    - Prowlarr:
        href: {{HOMEPAGE_VAR_PROWLARR_URL}}
        description: Torrent indexer
        icon: prowlarr.png
        widget:
            type: prowlarr
            url: {{HOMEPAGE_VAR_PROWLARR_URL}}
            key: {{HOMEPAGE_VAR_PROWLARR_API}}
    - Bazarr:
        href: {{HOMEPAGE_VAR_BAZARR_URL}}
        description: Subtitles downloader
        icon: bazarr.png
        widget:
            type: bazarr
            url: {{HOMEPAGE_VAR_BAZARR_URL}}
            key: {{HOMEPAGE_VAR_BAZARR_API}}

- Media:
    - Emby:
        href: {{HOMEPAGE_VAR_EMBY_URL}}
        description: Media player
        icon: emby.png
        widget:
            type: emby
            url: {{HOMEPAGE_VAR_EMBY_URL}}
            key: {{HOMEPAGE_VAR_EMBY_API}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false

- Network:
    - Traefik:
        href: {{HOMEPAGE_VAR_TRAEFIK_URL}}
        description: Reverse Proxy
        icon: traefik.png
        widget:
            type: traefik
            url: {{HOMEPAGE_VAR_TRAEFIK_URL}}
    - Technitium:
        href: {{HOMEPAGE_VAR_TECHNITIUM_URL}}
        description: DNS Server
        icon: technitium.png
        widget:
            type: technitium
            url: {{HOMEPAGE_VAR_TECHNITIUM_URL}}
            key: {{HOMEPAGE_VAR_TECHNITIUM_API}}
            range: LastDay
